import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, BadgeCheck, BarChart3, CheckCircle2, FileText, Plus, Quote, ShieldCheck, Sparkles } from "lucide-react";
import { ProofTabs } from "@/components/os/ProofTabs";
import { addOutcomeMetricAction, createExpansionOpportunityAction, createTestimonialAction, saveCaseStudyAction, updateOutcomeReportAction, updateTestimonialAction } from "@/lib/os/actions";
import { requireRole } from "@/lib/os/auth";
import { corporatePackages, formatAed } from "@/lib/os/corporate";
import { directionLabel, metricImprovement, metricProgress, proofEngagementLabels, proofStatusLabels } from "@/lib/os/proof";
import { readDatabase } from "@/lib/os/store";
import { formatDate } from "@/lib/os/utils";

export default async function OutcomeReportPage({ params }: { params: Promise<{ id: string }> }) {
  await requireRole(["super_admin", "academy_ops", "talent_ops"]);
  const { id } = await params;
  const database = await readDatabase();
  const report = database.outcomeReports.find((item) => item.id === id);
  if (!report) notFound();
  const account = report.accountId ? database.corporateAccounts.find((item) => item.id === report.accountId) : null;
  const deployment = report.deploymentId ? database.workforceDeployments.find((item) => item.id === report.deploymentId) : null;
  const cohort = report.cohortId ? database.cohorts.find((item) => item.id === report.cohortId) : null;
  const metrics = database.outcomeMetrics.filter((item) => item.outcomeReportId === report.id).sort((a, b) => a.sortOrder - b.sortOrder);
  const caseStudy = database.caseStudies.find((item) => item.outcomeReportId === report.id);
  const testimonials = database.testimonials.filter((item) => item.caseStudyId === caseStudy?.id || (report.accountId && item.accountId === report.accountId));
  const expansion = report.expansionOpportunityId ? database.corporateOpportunities.find((item) => item.id === report.expansionOpportunityId) : null;
  const today = new Date().toISOString().slice(0, 10);
  const verified = metrics.filter((item) => item.verified).length;

  return <div className="os-page os-proof-page os-proof-record">
    <Link href="/app/proof/reports" className="os-back-link"><ArrowLeft size={15} /> Outcome reports</Link>
    <div className="os-record-head os-proof-record-head"><div><div className="os-record-title"><h1>{report.title}</h1><span className={`os-proof-state is-${report.status}`}>{proofStatusLabels[report.status]}</span></div><p>{report.reportNumber} - {account?.companyName ?? cohort?.name ?? proofEngagementLabels[report.engagementType]}</p></div><div className="os-proof-record-actions"><span>{formatDate(report.periodStart)} - {formatDate(report.periodEnd)}</span>{expansion && <Link href={`/app/corporate/${expansion.id}`} className="os-table-action">Open expansion <ArrowRight size={13} /></Link>}</div></div>
    <ProofTabs active="reports" />

    <div className="os-proof-record-metrics">
      <div><span>Engagement</span><strong>{proofEngagementLabels[report.engagementType]}</strong><small>{deployment?.deploymentNumber ?? cohort?.code ?? "Direct engagement"}</small></div>
      <div><span>Evidence</span><strong>{verified}/{metrics.length}</strong><small>metrics verified</small></div>
      <div><span>Client approval</span><strong>{report.clientApproved ? "Approved" : "Pending"}</strong><small>{report.approvedAt ? formatDate(report.approvedAt) : "Publication locked"}</small></div>
      <div><span>Case study</span><strong>{caseStudy ? proofStatusLabels[caseStudy.status] : "Not built"}</strong><small>{caseStudy?.publicationConsent ? "Consent recorded" : "Consent pending"}</small></div>
      <div><span>Expansion</span><strong>{expansion ? formatAed(expansion.valueAed) : "Not opened"}</strong><small>{expansion?.stage ?? "Awaiting decision"}</small></div>
    </div>

    <div className="os-proof-detail-grid">
      <form action={updateOutcomeReportAction} className="os-panel os-proof-narrative">
        <input type="hidden" name="reportId" value={report.id} />
        <div className="os-panel-head"><div><span className="os-label">Approval record</span><h2>Outcome narrative</h2></div><FileText size={19} /></div>
        <div className="os-form-grid"><label className="full">Title<input name="title" defaultValue={report.title} required /></label><label>Status<select name="status" defaultValue={report.status}>{Object.entries(proofStatusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Period start<input type="date" name="periodStart" defaultValue={report.periodStart} required /></label><label>Period end<input type="date" name="periodEnd" defaultValue={report.periodEnd} required /></label><label className="full">Executive summary<textarea name="executiveSummary" rows={4} defaultValue={report.executiveSummary} /></label><label className="full">Baseline<textarea name="baselineSummary" rows={4} defaultValue={report.baselineSummary} /></label><label className="full">Observed outcomes<textarea name="outcomesSummary" rows={4} defaultValue={report.outcomesSummary} /></label><label className="full">Recommendations<textarea name="recommendations" rows={4} defaultValue={report.recommendations} /></label></div>
        <label className="os-check-line"><input type="checkbox" name="clientApproved" defaultChecked={report.clientApproved} /><span><strong>Client approval recorded</strong><small>Publishing is blocked until this approval is present.</small></span></label>
        <div className="os-form-actions"><button className="os-button" type="submit">Save report</button></div>
      </form>
      <aside className="os-proof-side-stack">
        <section className="os-panel os-proof-assurance"><div className="os-panel-head"><div><span className="os-label">Claim standard</span><h2>Publication gate</h2></div><ShieldCheck size={19} /></div><div className={metrics.length > 0 ? "is-complete" : ""}><CheckCircle2 size={15} /><span>Measures recorded<strong>{metrics.length}</strong></span></div><div className={verified === metrics.length && metrics.length > 0 ? "is-complete" : ""}><CheckCircle2 size={15} /><span>Evidence verified<strong>{verified}/{metrics.length}</strong></span></div><div className={report.clientApproved ? "is-complete" : ""}><CheckCircle2 size={15} /><span>Client approval<strong>{report.clientApproved ? "Yes" : "Pending"}</strong></span></div><div className={caseStudy?.publicationConsent ? "is-complete" : ""}><CheckCircle2 size={15} /><span>Publication consent<strong>{caseStudy?.publicationConsent ? "Yes" : "Pending"}</strong></span></div></section>
        {expansion ? <section className="os-panel os-proof-expansion"><span className="os-label">Expansion opened</span><h2>{expansion.title}</h2><strong>{formatAed(expansion.valueAed)}</strong><p>{expansion.nextStep}</p><Link href={`/app/corporate/${expansion.id}`}>Open corporate workspace <ArrowRight size={14} /></Link></section> : account && <form action={createExpansionOpportunityAction} className="os-panel os-proof-expansion"><input type="hidden" name="reportId" value={report.id} /><span className="os-label">Evidence to revenue</span><h2>Open expansion</h2><label>Opportunity title<input name="title" defaultValue={`${account.companyName} - expansion`} required /></label><label>Package<select name="package" defaultValue="enterprise">{Object.entries(corporatePackages).map(([value, item]) => <option value={value} key={value}>{item.label}</option>)}</select></label><label>Estimated value<input type="number" name="valueAed" min="0" defaultValue="25000" required /></label><label>Expected decision<input type="date" name="expectedCloseDate" /></label><label>Next decision<textarea name="nextStep" rows={3} defaultValue="Review verified outcomes and agree the next controlled workflow." required /></label><button className="os-button" type="submit"><Sparkles size={15} /> Create opportunity</button></form>}
      </aside>
    </div>

    <section className="os-panel os-proof-measures">
      <div className="os-panel-head"><div><span className="os-label">Baseline to result</span><h2>Measured outcomes</h2></div><BarChart3 size={19} /></div>
      <div className="os-proof-measure-list">{metrics.map((metric) => { const progress = metricProgress(metric); const improvement = metricImprovement(metric); return <article key={metric.id}><div><span className={metric.verified ? "is-verified" : ""}>{metric.verified ? "Verified" : "Unverified"}</span><strong>{metric.name}</strong><small>{metric.evidenceSource || "Evidence source not recorded"}</small></div><div><span>Baseline<strong>{metric.baselineValue} {metric.unit}</strong></span><span>Current<strong>{metric.currentValue} {metric.unit}</strong></span><span>Change<strong>{improvement > 0 ? "+" : ""}{improvement}%</strong></span></div><div><span style={{ width: `${progress ?? 0}%` }} /><small>{progress === null ? directionLabel(metric.direction) : `${progress}% of target`}</small></div></article>; })}{metrics.length === 0 && <div className="os-quiet-empty">Add the first baseline and result measure.</div>}</div>
      <form action={addOutcomeMetricAction} className="os-proof-inline-form"><input type="hidden" name="reportId" value={report.id} /><label>Metric<input name="name" placeholder="Weekly preparation time" required /></label><label>Unit<input name="unit" placeholder="hours" required /></label><label>Baseline<input type="number" step="0.01" name="baselineValue" required /></label><label>Current<input type="number" step="0.01" name="currentValue" required /></label><label>Target<input type="number" step="0.01" name="targetValue" /></label><label>Direction<select name="direction" defaultValue="increase"><option value="increase">Increase</option><option value="decrease">Decrease</option><option value="maintain">Maintain</option></select></label><label className="wide">Evidence source<input name="evidenceSource" placeholder="Approved time log, QA review or assessment export" /></label><label className="os-mini-check"><input type="checkbox" name="verified" /> Verified</label><button className="os-button" type="submit"><Plus size={15} /> Add measure</button></form>
    </section>

    <form action={saveCaseStudyAction} className="os-panel os-proof-content-form">
      <input type="hidden" name="reportId" value={report.id} />{caseStudy && <input type="hidden" name="caseStudyId" value={caseStudy.id} />}
      <div className="os-panel-head"><div><span className="os-label">Case-study asset</span><h2>{caseStudy ? "Shape the approved story" : "Build the case study"}</h2></div><BadgeCheck size={19} /></div>
      <div className="os-form-grid"><label>Title<input name="title" defaultValue={caseStudy?.title ?? report.title} required /></label><label>URL slug<input name="slug" defaultValue={caseStudy?.slug ?? ""} placeholder="team-outcome-case-study" required /></label><label>Client display name<input name="clientDisplayName" defaultValue={caseStudy?.clientDisplayName ?? account?.companyName ?? ""} required /></label><label>Industry<input name="industry" defaultValue={caseStudy?.industry ?? account?.industry ?? ""} /></label><label>Status<select name="status" defaultValue={caseStudy?.status ?? "draft"}>{Object.entries(proofStatusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="full">Summary<textarea name="summary" rows={3} defaultValue={caseStudy?.summary ?? report.executiveSummary} /></label><label className="full">Challenge<textarea name="challenge" rows={4} defaultValue={caseStudy?.challenge ?? report.baselineSummary} /></label><label className="full">Intervention<textarea name="intervention" rows={4} defaultValue={caseStudy?.intervention ?? ""} /></label><label className="full">Result<textarea name="result" rows={4} defaultValue={caseStudy?.result ?? report.outcomesSummary} /></label><label className="full">Evidence note<textarea name="evidenceNote" rows={3} defaultValue={caseStudy?.evidenceNote ?? ""} /></label></div>
      <div className="os-proof-consent-row"><label className="os-check-line"><input type="checkbox" name="publicationConsent" defaultChecked={caseStudy?.publicationConsent} /><span><strong>Written publication consent recorded</strong><small>Required for published status.</small></span></label><label className="os-check-line"><input type="checkbox" name="featured" defaultChecked={caseStudy?.featured} /><span><strong>Feature this case study</strong><small>Use only after approval.</small></span></label></div>
      <div className="os-form-actions"><button className="os-button" type="submit">Save case study</button></div>
    </form>

    <section className="os-panel os-testimonial-register">
      <div className="os-panel-head"><div><span className="os-label">Voice of the client</span><h2>Testimonials and permissions</h2></div><Quote size={19} /></div>
      <div>{testimonials.map((item) => <article key={item.id}><Quote size={18} /><blockquote>{item.quote}</blockquote><div><strong>{item.attributionName}</strong><small>{item.attributionTitle} - {item.attributionCompany}</small></div><form action={updateTestimonialAction}><input type="hidden" name="reportId" value={report.id} /><input type="hidden" name="testimonialId" value={item.id} /><select name="permission" defaultValue={item.permission}><option value="pending">Permission pending</option><option value="approved">Permission approved</option><option value="declined">Permission declined</option></select><select name="status" defaultValue={item.status}>{Object.entries(proofStatusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="os-table-action" type="submit">Update</button></form></article>)}</div>
      <form action={createTestimonialAction} className="os-proof-inline-form os-testimonial-form"><input type="hidden" name="reportId" value={report.id} /><input type="hidden" name="accountId" value={report.accountId ?? ""} /><input type="hidden" name="caseStudyId" value={caseStudy?.id ?? ""} /><label className="wide">Quote<textarea name="quote" rows={3} required /></label><label>Name<input name="attributionName" required /></label><label>Title<input name="attributionTitle" /></label><label>Company<input name="attributionCompany" defaultValue={account?.companyName ?? ""} /></label><label>Source<input name="source" placeholder="Email approval, survey or QA review" /></label><label>Permission<select name="permission" defaultValue="pending"><option value="pending">Pending</option><option value="approved">Approved</option><option value="declined">Declined</option></select></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="review">In review</option><option value="approved">Approved</option></select></label><label>Collected<input type="date" name="collectedAt" defaultValue={today} required /></label><button className="os-button" type="submit"><Plus size={15} /> Add testimonial</button></form>
    </section>
  </div>;
}
