import { ArrowRight, Handshake, Plus, UsersRound } from "lucide-react";
import { ProofTabs } from "@/components/os/ProofTabs";
import { createPartnerReferralAction, createPartnershipAction, updatePartnershipAction } from "@/lib/os/actions";
import { requireRole } from "@/lib/os/auth";
import { formatAed } from "@/lib/os/corporate";
import { readDatabase } from "@/lib/os/store";
import { formatDate } from "@/lib/os/utils";

const partnershipLabels = {
  business_community: "Business community", training_provider: "Training provider", professional_association: "Professional association",
  recruiter: "Recruiter", technology_provider: "Technology provider", referral_partner: "Referral partner",
} as const;

export default async function PartnershipsPage() {
  await requireRole(["super_admin", "academy_ops", "talent_ops"]);
  const database = await readDatabase();
  const active = database.partnerships.filter((item) => item.status === "active").length;
  const qualified = database.partnerReferrals.filter((item) => ["qualified", "converted"].includes(item.status));
  const influenced = qualified.reduce((sum, item) => sum + item.estimatedValueAed, 0);
  const conversion = database.partnerReferrals.length ? Math.round(database.partnerReferrals.filter((item) => item.status === "converted").length / database.partnerReferrals.length * 100) : 0;
  const today = new Date().toISOString().slice(0, 10);
  return <div className="os-page os-proof-page">
    <div className="os-page-head"><div><span className="os-label">Structured distribution</span><h1>Partnerships</h1><p>Build credible routes to market across business communities, training, talent and technology.</p></div></div>
    <ProofTabs active="partnerships" />
    <div className="os-proof-mini-command"><div><span>Partner pipeline</span><strong>{database.partnerships.length}</strong></div><div><span>Active partners</span><strong>{active}</strong></div><div><span>Qualified referrals</span><strong>{qualified.length}</strong></div><div><span>Influenced value</span><strong>{formatAed(influenced)}</strong></div><aside><UsersRound size={18} /><span>Referral conversion<strong>{conversion}%</strong></span></aside></div>

    <div className="os-partnership-grid"><section className="os-panel os-partnership-pipeline"><div className="os-panel-head"><div><span className="os-label">Relationship pipeline</span><h2>Partner motion</h2></div><Handshake size={19} /></div>{database.partnerships.map((item) => { const referrals = database.partnerReferrals.filter((referral) => referral.partnershipId === item.id); return <article key={item.id}><header><span>{item.organizationName.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div><strong>{item.organizationName}</strong><small>{partnershipLabels[item.type]}</small></div><span className={`os-proof-state is-${item.status}`}>{item.status}</span></header><p>{item.valueProposition}</p><div><span><strong>{referrals.length}</strong>referrals</span><span><strong>{formatAed(referrals.reduce((sum, referral) => sum + referral.estimatedValueAed, 0))}</strong>influenced</span><span><strong>{item.nextStepDueAt ? formatDate(item.nextStepDueAt) : "No date"}</strong>next move</span></div><form action={updatePartnershipAction}><input type="hidden" name="partnershipId" value={item.id} /><select name="status" defaultValue={item.status}><option value="prospect">Prospect</option><option value="conversation">Conversation</option><option value="active">Active</option><option value="paused">Paused</option><option value="closed">Closed</option></select><input name="nextStep" defaultValue={item.nextStep} aria-label={`Next step for ${item.organizationName}`} /><input type="date" name="nextStepDueAt" defaultValue={item.nextStepDueAt ?? ""} aria-label={`Next-step date for ${item.organizationName}`} /><button className="os-table-action" type="submit">Update</button></form></article>; })}</section>

    <form action={createPartnershipAction} className="os-panel os-proof-form os-partner-form"><div className="os-panel-head"><div><span className="os-label">New relationship</span><h2>Add a partner</h2></div><Plus size={18} /></div><div className="os-form-grid"><label className="full">Organisation<input name="organizationName" required /></label><label>Type<select name="type" defaultValue="business_community">{Object.entries(partnershipLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Status<select name="status" defaultValue="prospect"><option value="prospect">Prospect</option><option value="conversation">Conversation</option><option value="active">Active</option></select></label><label>Contact name<input name="contactName" /></label><label>Contact email<input type="email" name="contactEmail" /></label><label>Contact phone<input name="contactPhone" /></label><label>Website<input name="website" /></label><label className="full">Mutual value proposition<textarea name="valueProposition" rows={4} /></label><label className="full">Next step<input name="nextStep" /></label><label>Next-step due<input type="date" name="nextStepDueAt" /></label></div><div className="os-form-actions"><button className="os-button" type="submit">Add partner</button></div></form></div>

    <section className="os-panel os-referral-register"><div className="os-panel-head"><div><span className="os-label">Partner-sourced growth</span><h2>Referral register</h2></div><ArrowRight size={18} /></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Company</th><th>Partner</th><th>Referred</th><th>Status</th><th>Estimated value</th></tr></thead><tbody>{database.partnerReferrals.map((item) => { const partner = database.partnerships.find((entry) => entry.id === item.partnershipId); return <tr key={item.id}><td><strong className="os-cell-primary">{item.companyName}</strong><small>{item.contactName || "No contact named"}</small></td><td>{partner?.organizationName}</td><td>{formatDate(item.referredAt)}</td><td><span className={`os-proof-state is-${item.status}`}>{item.status}</span></td><td><strong>{formatAed(item.estimatedValueAed)}</strong></td></tr>; })}</tbody></table></div><form action={createPartnerReferralAction} className="os-proof-inline-form"><label>Partner<select name="partnershipId" required defaultValue=""><option value="" disabled>Select partner</option>{database.partnerships.map((item) => <option value={item.id} key={item.id}>{item.organizationName}</option>)}</select></label><label>Company<input name="companyName" required /></label><label>Contact<input name="contactName" /></label><label>Linked account<select name="accountId" defaultValue=""><option value="">Not linked</option>{database.corporateAccounts.map((item) => <option value={item.id} key={item.id}>{item.companyName}</option>)}</select></label><label>Linked opportunity<select name="opportunityId" defaultValue=""><option value="">Not linked</option>{database.corporateOpportunities.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Status<select name="status" defaultValue="referred"><option value="referred">Referred</option><option value="qualified">Qualified</option><option value="converted">Converted</option><option value="lost">Lost</option></select></label><label>Estimated value<input type="number" name="estimatedValueAed" min="0" defaultValue="0" /></label><label>Referred date<input type="date" name="referredAt" defaultValue={today} required /></label><label className="wide">Notes<input name="notes" /></label><button className="os-button" type="submit"><Plus size={15} /> Add referral</button></form></section>
  </div>;
}
