import { BarChart3, BriefcaseBusiness, Check, Plus, Target } from "lucide-react";
import { ProofTabs } from "@/components/os/ProofTabs";
import { createRepeatabilityBenchmarkAction, createRoleSpecialisationAction, updateRoleSpecialisationStatusAction } from "@/lib/os/actions";
import { requireRole } from "@/lib/os/auth";
import { proofEngagementLabels } from "@/lib/os/proof";
import { readDatabase } from "@/lib/os/store";
import { operatorTypes, statusLabel } from "@/lib/os/workforce";

export default async function RoleSpecialisationsPage() {
  await requireRole(["super_admin", "academy_ops", "talent_ops"]);
  const database = await readDatabase();
  const proven = database.roleSpecialisations.filter((item) => item.status === "proven").length;
  const activeDeployments = database.workforceDeployments.filter((item) => item.status === "active");
  const benchmarkSamples = database.repeatabilityBenchmarks.reduce((sum, item) => sum + item.sampleSize, 0);
  return <div className="os-page os-proof-page">
    <div className="os-page-head"><div><span className="os-label">Productised workforce roles</span><h1>Role specialisations</h1><p>Define what each operator role owns, the conditions it needs and the evidence required before scale.</p></div></div>
    <ProofTabs active="specialisations" />
    <div className="os-proof-mini-command"><div><span>Role blueprints</span><strong>{database.roleSpecialisations.length}</strong></div><div><span>Proven roles</span><strong>{proven}</strong></div><div><span>Active deployments</span><strong>{activeDeployments.length}</strong></div><div><span>Benchmark samples</span><strong>{benchmarkSamples}</strong></div></div>

    <section className="os-specialisation-grid">{database.roleSpecialisations.map((item) => { const operators = database.workforceOperators.filter((operator) => operator.operatorType === item.operatorType); const benchmarks = database.repeatabilityBenchmarks.filter((benchmark) => benchmark.specialisationId === item.id); return <article className="os-panel os-specialisation-card" key={item.id}><header><span><BriefcaseBusiness size={17} /></span><div><small>{operatorTypes[item.operatorType].label}</small><h2>{item.name}</h2></div><span className={`os-proof-state is-${item.status}`}>{statusLabel(item.status)}</span></header><p>{item.promise}</p><div className="os-specialisation-facts"><span><strong>{operators.length}</strong>operators</span><span><strong>{benchmarks.length}</strong>benchmarks</span><span><strong>{item.targetHoursSavedMonth}h</strong>target saved</span></div><div className="os-specialisation-list"><span className="os-label">Success measures</span>{item.successMetrics.map((metric) => <span key={metric}><Check size={12} />{metric}</span>)}</div><footer><small>{item.readinessRequirements}</small><form action={updateRoleSpecialisationStatusAction}><input type="hidden" name="specialisationId" value={item.id} /><select name="status" defaultValue={item.status}><option value="draft">Draft</option><option value="pilot">Pilot</option><option value="proven">Proven</option><option value="retired">Retired</option></select><button className="os-table-action" type="submit">Update</button></form></footer></article>; })}</section>

    <form action={createRoleSpecialisationAction} className="os-panel os-proof-form os-proof-compact-form">
      <div className="os-panel-head"><div><span className="os-label">Role architecture</span><h2>Create a specialisation</h2></div><Plus size={18} /></div>
      <div className="os-form-grid"><label>Name<input name="name" placeholder="AI Customer Experience Operator" required /></label><label>URL slug<input name="slug" placeholder="ai-customer-experience-operator" required /></label><label>Operator family<select name="operatorType" defaultValue="customer_experience">{Object.entries(operatorTypes).map(([value, item]) => <option value={value} key={value}>{item.label}</option>)}</select></label><label>Target department<input name="targetDepartment" required /></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="pilot">Pilot</option><option value="proven">Proven</option></select></label><label>Target hours saved / month<input type="number" name="targetHoursSavedMonth" min="0" defaultValue="20" required /></label><label className="full">Role promise<textarea name="promise" rows={3} required /></label><label className="full">Responsibilities, separated by commas<input name="responsibilities" /></label><label className="full">Approved tools, separated by commas<input name="approvedTools" /></label><label className="full">Success metrics, separated by commas<input name="successMetrics" /></label><label className="full">Client readiness requirements<textarea name="readinessRequirements" rows={4} /></label></div>
      <div className="os-form-actions"><button className="os-button" type="submit">Create role blueprint</button></div>
    </form>

    <section className="os-panel os-benchmark-register"><div className="os-panel-head"><div><span className="os-label">Evidence threshold</span><h2>Repeatability benchmarks</h2></div><BarChart3 size={19} /></div><div>{database.repeatabilityBenchmarks.map((item) => { const specialisation = database.roleSpecialisations.find((entry) => entry.id === item.specialisationId); return <article key={item.id}><div><strong>{item.metricName}</strong><small>{specialisation?.name ?? proofEngagementLabels[item.engagementType]} - {item.industry}</small></div><span><strong>{item.medianBaseline}</strong><small>baseline {item.unit}</small></span><span><strong>{item.medianResult}</strong><small>median result</small></span><span><strong>{item.improvementPercent}%</strong><small>change</small></span><span className={item.sampleSize >= item.evidenceThreshold ? "is-ready" : ""}><strong>{item.sampleSize}/{item.evidenceThreshold}</strong><small>{item.status}</small></span></article>; })}</div><form action={createRepeatabilityBenchmarkAction} className="os-proof-inline-form"><label>Role<select name="specialisationId" defaultValue=""><option value="">Cross-role</option>{database.roleSpecialisations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Engagement<select name="engagementType" defaultValue="workforce">{Object.entries(proofEngagementLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Industry<input name="industry" defaultValue="Cross-industry" required /></label><label>Metric<input name="metricName" required /></label><label>Unit<input name="unit" required /></label><label>Samples<input type="number" name="sampleSize" min="1" defaultValue="1" required /></label><label>Baseline<input type="number" name="medianBaseline" step="0.01" required /></label><label>Result<input type="number" name="medianResult" step="0.01" required /></label><label>Change %<input type="number" name="improvementPercent" step="0.01" required /></label><label>Threshold<input type="number" name="evidenceThreshold" min="1" defaultValue="3" required /></label><label>Status<select name="status" defaultValue="emerging"><option value="emerging">Emerging</option><option value="validated">Validated</option><option value="reference">Reference</option></select></label><button className="os-button" type="submit"><Target size={15} /> Add benchmark</button></form></section>
  </div>;
}
