import { notFound } from "next/navigation";
import Link from "next/link";
import { Breadcrumbs, CTA, SectionHeading } from "@/components/UI";
import { JsonLd } from "@/components/JsonLd";
import { industries } from "@/lib/site";
import { breadcrumbSchema, pageMetadata, serviceSchema } from "@/lib/seo";

export function generateStaticParams(){return industries.map(i=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=industries.find(i=>i.slug===slug);if(!item)return {};return pageMetadata({title:`AI Workforce and Training for ${item.name} UAE`,description:item.summary,path:`/industries/${item.slug}`,keywords:[`AI for ${item.name}`,`AI training for ${item.name}`,`${item.name} AI workflows UAE`]});}
export default async function IndustryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=industries.find(i=>i.slug===slug);if(!item)notFound();const path=`/industries/${item.slug}`;return <><JsonLd data={[serviceSchema({name:`AI Workforce and Team Enablement for ${item.name}`,description:item.summary,path,audience:`${item.name} organisations in the UAE`,offers:["Team AI Enablement","AI Readiness Assessment","AI Workforce"]}),breadcrumbSchema([{name:"Home",path:"/"},{name:"Industries",path:"/#industries"},{name:item.name,path}])]}/><section className="page-hero"><div className="container"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Industries",href:"/#industries"},{label:item.name}]}/><span className="eyebrow">Industry application</span><h1>AI capability for {item.name.toLowerCase()} teams.</h1><p>{item.summary}</p></div></section><section><div className="container split"><div><SectionHeading eyebrow="Common challenges" title="Where capability and workflow gaps appear."/><div className="check-list">{item.challenges.map(x=><div key={x}><i>!</i><p>{x}</p></div>)}</div></div><div><SectionHeading eyebrow="Potential outcomes" title="What a practical programme can create."/><div className="check-list">{item.outcomes.map(x=><div key={x}><i>✓</i><p>{x}</p></div>)}</div></div></div></section><section className="dark-section"><div className="container"><SectionHeading eyebrow="Relevant solutions" title="Choose the right intervention for your organisation."/><div className="cards-3"><Link className="card" href="/academy/team-ai-enablement"><h3>Team AI Enablement</h3><p>Role-specific training, workflow design and implementation support.</p><span className="text-link light">Explore programme →</span></Link><Link className="card" href="/enterprise/ai-readiness-assessment"><h3>AI Readiness Assessment</h3><p>Identify opportunities, capability gaps, risks and priority next steps.</p><span className="text-link light">Explore assessment →</span></Link><Link className="card" href="/ai-workforce"><h3>AI Workforce</h3><p>Deploy trained professionals into clearly scoped, managed roles.</p><span className="text-link light">Explore workforce →</span></Link></div></div></section><CTA title={`Build responsible AI capability in ${item.name.toLowerCase()}.`} text="Discuss your team, workflows and current stage of adoption with Lymora." /></>}
